### ISSUE TITLE
Doesn't show anything despite me starring the repo

### ISSUE THREAD

**Issue by nikitavoloboev** [tipsy/profile-summary-for-github#83]
![2018-03-30 at 14 37](https://user-images.githubusercontent.com/6391776/38137900-e167a21a-3427-11e8-9771-0beacc487c56.png)

However I have starred the repo:

![2018-03-30 at 14 37](https://user-images.githubusercontent.com/6391776/38137905-ea90c268-3427-11e8-9698-b6f0868a2add.png)

**Comment by iProdigy** [comment]
Strange. 

1. Can confirm you have starred the repo
2. Can confirm that the heroku instance won't resolve your profile
3. Yet, [a local instance of the app correctly displays your profile](https://i.imgur.com/Jr1wLjL.png).

**Comment by iProdigy** [comment]
Appears to be a duplicate of #82.

**Comment by iProdigy** [comment]
I have traced the problem to [how the application determines whether a user has starred the project](https://github.com/tipsy/profile-summary-for-github/blob/master/src/main/kotlin/app/UserCtrl.kt#L53).; running the app in unrestricted mode (don't need to star) [yields the profile correctly](https://i.imgur.com/rvSeFhq.png). In particular, I think the issue is in how many repos you have starred (and that we are not in your most recent 100 stars)... I will submit a PR to fix this ASAP

**Comment by tipsy** [comment]
@nikitavoloboev, your profile works after @iProdigy's fix: https://profile-summary-for-github.com/user/nikitavoloboev
